import Head from 'next/head'
import loader from "@monaco-editor/loader";
import { useEffect } from 'react';
const recordingId = "41466cc2-0572-4959-be1d-d2dbd91460ac"

const isServer = () => typeof window === 'undefined';

async function createSession(recordingId) {
  if (isServer()) {
    return
  }
  console.log('not server')
  const socket = await import("./socket")
  console.log({socket})
  socket.initSocket()
  const { sessionId } = await socket.sendMessage("Recording.createSession", {
    recordingId,
  })

  return {sessionId, socket}
}

async function createEditor() {
  loader.init().then((monaco) => {
    const wrapper = document.getElementById("editor");
    wrapper.style.height = "100vh";
    const properties = {
      value: "function hello() {\n\talert('Hello world!');\n}",
      language: "javascript",
      IEditorMinimapOptions: {
        enabled: false
      },

      // IEditorOptions: {
      //   fontSize: 34,
      //   lineHeight: 40
      // },

      lineNumbers: "off",
      roundedSelection: false,
      scrollBeyondLastLine: false,
      readOnly: true,
      theme: "vs-dark",
      fontSize: "16px"
    };
    editor = monaco.editor.create(wrapper, properties);

    // import('monaco-themes/themes/Monokai.json')
    //   .then(data => {
    //       // monaco.editor.defineTheme('monokai', data);
    //       // monaco.editor.setTheme('monokai');
    //   })
  })
}

let editor;
export default function Home() {
  useEffect(()=> {
    createEditor();
  }, [])

  useEffect(() => {
    createSession(recordingId).then(async ({socket, sessionId}) => {
      console.log({sessionId, recordingId})


      socket.client.Debugger.addNewSourceListener(source => {
        console.log(source)
      })

      socket.client.Debugger.findSources({}, sessionId)

      const {contents} = await socket.client.Debugger.getSourceContents({sourceId: "1"}, sessionId)
      console.log({contents})
      editor.setValue(contents)
    })
  },[])
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <div id="editor"></div>
      </main>

    </div>
  )
}
